version: '3'
services:
  web:
    container_name: 'expertplat_frontend'
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always 
    ports:
      - '80:80'
      - '443:443'

 
     
  
   

